apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  #how to find all the pods to create
  selector:
    matchLabels:
      app: auth
  # how to create the pods
  template:
    metadata:
      labels:
        app: auth
    #how should the pods behace
    spec:
      containers:
      - name: auth
        image: ganavijayaram/auth
        #List of environment avriable for this pod
        #in our case we created secret object and we are taking he value from there
        env:
          - name: JWT_KEY #this is the name of the env variable which will be used in the pod
            valueFrom:
              secretKeyRef:
                name: jwt-secret #name of the secret
                key: JWT_KEY #name of the env which we used while creating the secret
        #image: us.gcr.io/vintage-galleria-dev/auth
        
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec: 
  #How to select
  selector:
    # default type is ClusterIP
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000

